version: "2.1"
services:
  products-ms:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      products-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I products-ms:3000/products-ms/resources/products/ --fail"
      interval: 20s
      retries: 10

  products-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: products-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
